// src/lib/api.js
// Google Gemini API integration with local deterministic fallback engine

import useAppStore from '../store/useAppStore';
import { simulateStream } from './utils';
import { runFallbackEngine } from './fallbackEngine';
import {
  IMPROVE_SYSTEM_PROMPT,
  WORKFLOW_SYSTEM_PROMPT,
  DIAGNOSE_SYSTEM_PROMPT,
  CLARIFY_SYSTEM_PROMPT,
} from './prompts';

async function callGemini(systemPrompt, userPrompt, modelName) {
  const store = useAppStore.getState();
  const apiKey = store.geminiKey;
  
  if (!apiKey) {
    throw Object.assign(new Error('NO_KEY'), {
      userMessage: 'No Gemini API key configured. Please configure your environment variables (VITE_GEMINI_KEY).',
    });
  }

  const requestedModel = modelName.replace('google/', '');

  // Ordered list of candidate models to try. Starts with requested model, then falls back to others.
  const candidates = [
    requestedModel,
    'gemini-2.5-pro',
    'gemini-2.5-flash',
    'gemini-2.0-flash',
    'gemini-1.5-pro',
    'gemini-1.5-flash'
  ];

  // Remove duplicates while keeping order
  const uniqueCandidates = [...new Set(candidates)];
  let lastError;

  for (const model of uniqueCandidates) {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
    store.setKeyStatus('active');

    try {
      const res = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [
            {
              role: 'user',
              parts: [{ text: userPrompt }]
            }
          ],
          systemInstruction: {
            parts: [{ text: systemPrompt }]
          },
          generationConfig: {
            temperature: 0.3,
            responseMimeType: 'application/json'
          }
        }),
        signal: AbortSignal.timeout(60000),
      });

      if (!res.ok) {
        const errText = await res.text().catch(() => '');
        let errMsg = `HTTP ${res.status}`;
        try {
          const parsed = JSON.parse(errText);
          errMsg = parsed?.error?.message || errMsg;
        } catch {}
        throw new Error(errMsg);
      }

      const data = await res.json();
      const content = data?.candidates?.[0]?.content?.parts?.[0]?.text;
      if (!content) {
        throw new Error('Empty response from Gemini API');
      }

      // If we succeeded with a model other than the requested one, update store and localStorage
      if (model !== requestedModel) {
        console.warn(`Requested model '${requestedModel}' failed, successfully fell back to '${model}'.`);
        store.setSelectedModel(model);
      }

      store.setKeyStatus('healthy');
      return content;
    } catch (err) {
      console.warn(`Gemini call failed for model '${model}': ${err.message}. Trying next candidate...`);
      lastError = err;
    }
  }

  // If we reach here, all candidates failed
  store.setKeyStatus('error');
  throw Object.assign(new Error(`All Gemini models failed. Last error: ${lastError?.message}`), {
    userMessage: `Gemini API call failed for all models. Last error: ${lastError?.message}`
  });
}

// ── Public API ──────────────────────────────────────────────

export async function improvePrompt(
  { prompt, taskType, targetModel, outputStyle, tone, mode = 'improve' },
  { onChunk } = {}
) {
  const { selectedModel } = useAppStore.getState();

  const userMessage = `Please improve this prompt:

"${prompt}"

Configuration:
- Task Type: ${taskType || 'auto-detect'}
- Target Model: ${targetModel || 'generic'}
- Output Style: ${outputStyle || 'structured'}
- Tone: ${tone || 'professional'}
- Mode: ${mode}`;

  try {
    const content = await callGemini(IMPROVE_SYSTEM_PROMPT, userMessage, selectedModel);
    
    useAppStore.getState().setFallbackActive(false);
    useAppStore.getState().setFallbackNote('');
    
    if (onChunk) {
      await simulateStream(content, onChunk);
      return content;
    }
    return {
      choices: [
        {
          message: {
            content: content
          }
        }
      ]
    };
  } catch (err) {
    useAppStore.getState().setFallbackActive(true);
    useAppStore.getState().setFallbackNote("Generated by deterministic fallback engine. No AI API was used. Results are rule-based.");
    
    const fallbackResult = runFallbackEngine(prompt, taskType, targetModel, 'improve');
    const improveResponse = {
      quick_version: fallbackResult.quickVersion,
      advanced_version: fallbackResult.advancedVersion,
      diagnosis: fallbackResult.diagnosis.weaknesses.map(w => ({
        category: w.category,
        severity: w.severity,
        title: w.title,
        description: w.description
      })),
      alternatives: fallbackResult.alternatives
    };
    const jsonString = JSON.stringify(improveResponse, null, 2);

    if (onChunk) {
      await simulateStream(jsonString, onChunk);
      return jsonString;
    }
    return {
      choices: [
        {
          message: {
            content: jsonString
          }
        }
      ]
    };
  }
}

export async function runDiagnosis({ prompt }) {
  const { selectedModel } = useAppStore.getState();

  try {
    const content = await callGemini(
      DIAGNOSE_SYSTEM_PROMPT,
      `Analyze this prompt:\n\n"${prompt}"`,
      selectedModel
    );
    useAppStore.getState().setFallbackActive(false);
    useAppStore.getState().setFallbackNote('');

    return {
      choices: [
        {
          message: {
            content: content
          }
        }
      ]
    };
  } catch (err) {
    useAppStore.getState().setFallbackActive(true);
    useAppStore.getState().setFallbackNote("Generated by deterministic fallback engine. No AI API was used. Results are rule-based.");

    const fallbackResult = runFallbackEngine(prompt, null, null, 'improve');
    const categories = [
      {
        name: "Role Definition",
        max_score: 15,
        score: fallbackResult.diagnosis.weaknesses.some(w => w.category === "Role Definition") ? 0 : 15,
        status: fallbackResult.diagnosis.weaknesses.some(w => w.category === "Role Definition") ? "missing" : "good",
        finding: fallbackResult.diagnosis.weaknesses.find(w => w.category === "Role Definition")?.description || "Persona is correctly and explicitly defined.",
        recommendation: fallbackResult.diagnosis.weaknesses.find(w => w.category === "Role Definition")?.description || "Maintain persona constraints."
      },
      {
        name: "Task Clarity",
        max_score: 15,
        score: fallbackResult.diagnosis.weaknesses.some(w => w.category === "Task Clarity") ? 0 : 15,
        status: fallbackResult.diagnosis.weaknesses.some(w => w.category === "Task Clarity") ? "missing" : "good",
        finding: fallbackResult.diagnosis.weaknesses.find(w => w.category === "Task Clarity")?.description || "Core objective is clearly stated.",
        recommendation: fallbackResult.diagnosis.weaknesses.find(w => w.category === "Task Clarity")?.description || "Keep using direct action verbs."
      },
      {
        name: "Context & Background",
        max_score: 10,
        score: fallbackResult.diagnosis.weaknesses.some(w => w.category === "Context & Background") ? 0 : 10,
        status: fallbackResult.diagnosis.weaknesses.some(w => w.category === "Context & Background") ? "missing" : "good",
        finding: fallbackResult.diagnosis.weaknesses.find(w => w.category === "Context & Background")?.description || "Background context is sufficient.",
        recommendation: fallbackResult.diagnosis.weaknesses.find(w => w.category === "Context & Background")?.description || "Ensure domain info remains clean."
      },
      {
        name: "Output Format",
        max_score: 15,
        score: fallbackResult.diagnosis.weaknesses.some(w => w.category === "Output Format") ? 0 : 15,
        status: fallbackResult.diagnosis.weaknesses.some(w => w.category === "Output Format") ? "missing" : "good",
        finding: fallbackResult.diagnosis.weaknesses.find(w => w.category === "Output Format")?.description || "Format requirement details are clear.",
        recommendation: fallbackResult.diagnosis.weaknesses.find(w => w.category === "Output Format")?.description || "Keep using format keywords."
      },
      {
        name: "Audience Specification",
        max_score: 10,
        score: fallbackResult.diagnosis.weaknesses.some(w => w.category === "Audience Specification") ? 0 : 10,
        status: fallbackResult.diagnosis.weaknesses.some(w => w.category === "Audience Specification") ? "missing" : "good",
        finding: fallbackResult.diagnosis.weaknesses.find(w => w.category === "Audience Specification")?.description || "Audience target group is specified.",
        recommendation: fallbackResult.diagnosis.weaknesses.find(w => w.category === "Audience Specification")?.description || "Review vocabulary target depth."
      },
      {
        name: "Constraints & Guardrails",
        max_score: 15,
        score: fallbackResult.diagnosis.weaknesses.some(w => w.category === "Constraints & Guardrails") ? 0 : 15,
        status: fallbackResult.diagnosis.weaknesses.some(w => w.category === "Constraints & Guardrails") ? "missing" : "good",
        finding: fallbackResult.diagnosis.weaknesses.find(w => w.category === "Constraints & Guardrails")?.description || "Boundaries and constraints are clearly set.",
        recommendation: fallbackResult.diagnosis.weaknesses.find(w => w.category === "Constraints & Guardrails")?.description || "Set specific criteria boundaries."
      },
      {
        name: "Examples (Few-shot)",
        max_score: 10,
        score: fallbackResult.diagnosis.weaknesses.some(w => w.category === "Examples (Few-shot)") ? 0 : 10,
        status: fallbackResult.diagnosis.weaknesses.some(w => w.category === "Examples (Few-shot)") ? "missing" : "good",
        finding: fallbackResult.diagnosis.weaknesses.find(w => w.category === "Examples (Few-shot)")?.description || "Example block is present.",
        recommendation: fallbackResult.diagnosis.weaknesses.find(w => w.category === "Examples (Few-shot)")?.description || "Include 1-2 examples of inputs."
      },
      {
        name: "Scope Boundaries",
        max_score: 10,
        score: fallbackResult.diagnosis.weaknesses.some(w => w.title === "High Ambiguity") ? 0 : 10,
        status: fallbackResult.diagnosis.weaknesses.some(w => w.title === "High Ambiguity") ? "weak" : "good",
        finding: fallbackResult.diagnosis.weaknesses.find(w => w.title === "High Ambiguity")?.description || "Vague language levels are low.",
        recommendation: fallbackResult.diagnosis.weaknesses.find(w => w.title === "High Ambiguity")?.description || "Refrain from general descriptors."
      }
    ];

    const diagResponse = {
      overall_score: fallbackResult.score,
      categories,
      priority_actions: fallbackResult.diagnosis.weaknesses.map(w => ({
        priority: w.severity === "high" || w.severity === "critical" ? "critical" : "important",
        action: w.title,
        category: w.category
      }))
    };

    const jsonString = JSON.stringify(diagResponse, null, 2);
    return {
      choices: [
        {
          message: {
            content: jsonString
          }
        }
      ]
    };
  }
}

export async function buildWorkflowPrompt(
  { prompt, modules, outputRequirements, integrationContext, expectedOutputFormat },
  { onChunk } = {}
) {
  const { selectedModel } = useAppStore.getState();

  const userMessage = `Build a complete workflow prompt system for:

Base prompt/idea: "${prompt}"

Configuration:
- Workflow modules: ${modules?.join(', ') || 'general'}
- Integration platform: ${integrationContext || 'other'}
- Expected output format: ${expectedOutputFormat || 'json'}
- Include system prompt: ${outputRequirements?.includeSystemPrompt}
- Include user template: ${outputRequirements?.includeUserTemplate}
- Include variable placeholders: ${outputRequirements?.includeVariables}
- Include guardrails: ${outputRequirements?.includeGuardrails}
- Include output schema: ${outputRequirements?.includeSchema}
- Include few-shot examples: ${outputRequirements?.includeFewShot}`;

  try {
    const content = await callGemini(WORKFLOW_SYSTEM_PROMPT, userMessage, selectedModel);
    useAppStore.getState().setFallbackActive(false);
    useAppStore.getState().setFallbackNote('');

    if (onChunk) {
      await simulateStream(content, onChunk);
      return content;
    }
    return {
      choices: [
        {
          message: {
            content: content
          }
        }
      ]
    };
  } catch (err) {
    useAppStore.getState().setFallbackActive(true);
    useAppStore.getState().setFallbackNote("Generated by deterministic fallback engine. No AI API was used. Results are rule-based.");

    const fallbackResult = runFallbackEngine(prompt, null, null, 'workflow', 'json_output', integrationContext);
    const system = fallbackResult.workflowSystem;
    const workflowResponse = {
      system_prompt: system.system_prompt,
      user_template: system.user_template,
      variables: system.variables,
      guardrails: system.guardrails,
      output_schema: system.output_schema,
      integration_notes: system.integration_notes,
      few_shot_examples: system.few_shot_examples
    };
    const jsonString = JSON.stringify(workflowResponse, null, 2);

    if (onChunk) {
      await simulateStream(jsonString, onChunk);
      return jsonString;
    }
    return {
      choices: [
        {
          message: {
            content: jsonString
          }
        }
      ]
    };
  }
}

export async function askClarifyingQuestions({ prompt, taskType }) {
  const { selectedModel } = useAppStore.getState();

  try {
    const content = await callGemini(
      CLARIFY_SYSTEM_PROMPT,
      `Prompt: "${prompt}"\nTask type hint: ${taskType || 'unknown'}`,
      selectedModel
    );
    useAppStore.getState().setFallbackActive(false);
    useAppStore.getState().setFallbackNote('');

    return {
      choices: [
        {
          message: {
            content: content
          }
        }
      ]
    };
  } catch (err) {
    useAppStore.getState().setFallbackActive(true);
    useAppStore.getState().setFallbackNote("Generated by deterministic fallback engine. No AI API was used. Results are rule-based.");

    const clarifyResponse = {
      questions: [
        {
          id: "q1",
          question: `What is the target audience context for: "${prompt.slice(0, 40)}..."?`,
          why: "Understanding the end reader profile helps refine vocabulary depth.",
          options: ["Technical Experts", "General Public", "Executives/Business"]
        },
        {
          id: "q2",
          question: "What is your preferred output format structure?",
          why: "Standardizing output layout prevents post-generation reformatting.",
          options: ["JSON Schema", "Bullet points", "Paragraph narrative"]
        }
      ]
    };
    const jsonString = JSON.stringify(clarifyResponse, null, 2);
    return {
      choices: [
        {
          message: {
            content: jsonString
          }
        }
      ]
    };
  }
}

export async function testApiKey(apiKey) {
  try {
    const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{ role: 'user', parts: [{ text: 'ping' }] }],
        generationConfig: { maxOutputTokens: 5 }
      }),
      signal: AbortSignal.timeout(10000),
    });

    if (res.status === 400) {
      const errText = await res.text().catch(() => '');
      if (errText.includes('API key not valid')) {
        return { valid: false, reason: 'Invalid API key' };
      }
    }
    if (res.status === 403) return { valid: false, reason: 'Permission denied / Invalid API key' };
    if (res.status === 429) return { valid: true, reason: 'Key valid but rate limited' };
    if (!res.ok) return { valid: false, reason: `HTTP ${res.status}` };
    return { valid: true, reason: 'Healthy' };
  } catch (e) {
    return { valid: false, reason: e.message };
  }
}
